### ISSUE TITLE
Add support for PHP 8.x, please

### ISSUE THREAD

**Issue by stevenmaguire** [dsposito/argo#16]
Great package - thank you for maintaining it!

I have a project that depends on this package. That project is currently upgrading to 8.x and that upgrade is blocked because this package's composer.json does not indicate it is compatible with PHP v 8.x.

```
  Problem 1
    - Root composer.json requires dsposito/argo ^2.0 -> satisfiable by dsposito/argo[v2.0.0].
    - dsposito/argo v2.0.0 requires php ^7.0 -> your php version (8.0.20) does not satisfy that requirement.
```

Are you able to resolve that?

If the code is already compliant with PHP 8.x then the fix would be a simple update to your composer.json and a new release.

Something like this:

<img width="290" alt="CleanShot 2022-06-23 at 09 43 35@2x" src="https://user-images.githubusercontent.com/1851973/175327415-3a1cd89c-b70c-4824-b420-1488e79857a1.png">

**Comment by stevenmaguire** [comment]
@dsposito do you have any thoughts on addressing this issue?

**Comment by dsposito** [comment]
Hi @stevenmaguire, thanks for the comment - I'm glad you've found this project useful!

To be honest, it has been a few years since I've developed in PHP. However, according to this project's composer.json it looks like it should work fine with PHP 7+ https://github.com/dsposito/argo/blob/master/composer.json#L15

So it should work ok with PHP 8.0.29

Can you make sure you're installing the production / non-dev version of this package? The require-dev specifies some version-locked dependencies. If you're installing the dev (default) version then one of those dependencies might be causing your issue above. https://github.com/dsposito/argo/blob/master/composer.json#L18-L20

Try this:
```
composer require dsposito/argo --no-dev
```

Feel free to submit a PR to update the version numbers in composer.json if you figure out the issue!

**Comment by stevenmaguire** [comment]
There is no semver release that includes the changes to the composer.json file that you mention. The latest release is still 2.0.0 and that composer directive is "^7.0".

https://github.com/dsposito/argo/blob/07a764f99511cb512a59017ea136c644485d5a66/composer.json#L15

Perhaps you can simply cut a new release >2.0.0 and everything will be just fine?

**Comment by dsposito** [comment]
Done! Try now: https://packagist.org/packages/dsposito/argo#v2.1.0

**Comment by stevenmaguire** [comment]
Thanks @dsposito! I think anyone who is moving on to PHP 8 will find this change acceptable :)
